user_info =  [
    {
      "employee_id": 565,
      "employee_name_eng": "M. Mesbahul Alam",
      "employee_name_bng": "মুঃ মেসবাহুল আলম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "",
      "designation_bng": "সহকারি প্রোগ্রামার",
      "user_id": 588,
      "username": "200000000141",
      "user_image": None
    },
    {
      "employee_id": 63171,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ মোশারফ হোসেন",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "",
      "designation_bng": "সহকারি প্রোগ্রামার",
      "user_id": 63388,
      "username": "200000060897",
      "user_image": None
    },
    {
      "employee_id": 565,
      "employee_name_eng": "M. Mesbahul Alam",
      "employee_name_bng": "মুঃ মেসবাহুল আলম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "",
      "designation_bng": "সহকারি প্রোগ্রামার",
      "user_id": 588,
      "username": "200000000141",
      "user_image": None
    },
    {
      "employee_id": 63171,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ মোশারফ হোসেন",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "",
      "designation_bng": "সহকারি প্রোগ্রামার",
      "user_id": 63388,
      "username": "200000060897",
      "user_image": None
    },
    {
      "employee_id": 565,
      "employee_name_eng": "M. Mesbahul Alam",
      "employee_name_bng": "মুঃ মেসবাহুল আলম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "",
      "designation_bng": "সহকারি প্রোগ্রামার",
      "user_id": 588,
      "username": "200000000141",
      "user_image": None
    },
    {
      "employee_id": 63171,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ মোশারফ হোসেন",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "",
      "designation_bng": "সহকারি প্রোগ্রামার",
      "user_id": 63388,
      "username": "200000060897",
      "user_image": None
    },
    {
      "employee_id": 565,
      "employee_name_eng": "M. Mesbahul Alam",
      "employee_name_bng": "মুঃ মেসবাহুল আলম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "",
      "designation_bng": "সহকারি প্রোগ্রামার",
      "user_id": 588,
      "username": "200000000141",
      "user_image": None
    },
    {
      "employee_id": 563,
      "employee_name_eng": "Muhammad Anwar Hossain",
      "employee_name_bng": "মোহাম্মদ আনোয়ার হোসেন",
      "office_id": 57,
      "office_unit_id": 885,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সেবা উন্নয়ন ও রক্ষণাবেক্ষণ শাখা",
      "unit_name_en": "e-Service Dev. & Maintenance Section",
      "designation_eng": "Maintenance Engineer",
      "designation_bng": "মেইন্টেনেন্স ইঞ্জিনিয়ার",
      "user_id": 586,
      "username": "200000000139",
      "user_image": None
    },
    {
      "employee_id": 564,
      "employee_name_eng": "Md. Shariful Islam",
      "employee_name_bng": "মোঃ শরিফুল ইসলাম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "System Analyst",
      "designation_bng": "প্রোগ্রামার",
      "user_id": 587,
      "username": "200000000140",
      "user_image": None
    },
    {
      "employee_id": 565,
      "employee_name_eng": "M. Mesbahul Alam",
      "employee_name_bng": "মুঃ মেসবাহুল আলম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "System Analyst",
      "designation_bng": "প্রোগ্রামার",
      "user_id": 588,
      "username": "200000000141",
      "user_image": None
    },
    {
      "employee_id": 564,
      "employee_name_eng": "Md. Shariful Islam",
      "employee_name_bng": "মোঃ শরিফুল ইসলাম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "System Analyst",
      "designation_bng": "প্রোগ্রামার",
      "user_id": 587,
      "username": "200000000140",
      "user_image": None
    },
    {
      "employee_id": 565,
      "employee_name_eng": "M. Mesbahul Alam",
      "employee_name_bng": "মুঃ মেসবাহুল আলম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "System Analyst",
      "designation_bng": "প্রোগ্রামার",
      "user_id": 588,
      "username": "200000000141",
      "user_image": None
    },
    {
      "employee_id": 564,
      "employee_name_eng": "Md. Shariful Islam",
      "employee_name_bng": "মোঃ শরিফুল ইসলাম",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "System Analyst",
      "designation_bng": "প্রোগ্রামার",
      "user_id": 587,
      "username": "200000000140",
      "user_image": None
    },
    {
      "employee_id": 1910,
      "employee_name_eng": "Md. Boshir Ahmmed ",
      "employee_name_bng": "মোঃ বশীর আহমেদ ",
      "office_id": 57,
      "office_unit_id": 861,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "উন্নয়ন শাখা",
      "unit_name_en": "Development Section",
      "designation_eng": "Assistant Secretary",
      "designation_bng": "সহকারী সচিব",
      "user_id": 1932,
      "username": "200000001155",
      "user_image": None
    },
    {
      "employee_id": 658,
      "employee_name_eng": "Russel Monzoor",
      "employee_name_bng": "রাসেল মনজুর",
      "office_id": 57,
      "office_unit_id": 887,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "গবেষণা ও বৃত্তি শাখা",
      "unit_name_en": "Research & Scholarship Section",
      "designation_eng": "Senior Assistant Secretary",
      "designation_bng": "সিনিয়র সহকারী সচিব",
      "user_id": 680,
      "username": "100000015765",
      "user_image": None
    },
    {
      "employee_id": 562,
      "employee_name_eng": " Md. Nobir Uddin",
      "employee_name_bng": "মোঃ নবীর উদ্দীন",
      "office_id": 57,
      "office_unit_id": 883,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সিস্টেম ডেভেলপমেন্ট এবং অপারেশন অধিশাখা",
      "unit_name_en": "System Development & Operation Branch",
      "designation_eng": "",
      "designation_bng": "সিনিয়র সিস্টেম এনালিস্ট",
      "user_id": 585,
      "username": "200000000138",
      "user_image": None
    },
    {
      "employee_id": 656,
      "employee_name_eng": "Md. Khairul Amin",
      "employee_name_bng": "মোঃ খায়রুল আমীন",
      "office_id": 57,
      "office_unit_id": 872,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সংস্থা-১ শাখা",
      "unit_name_en": "Organization-1 Section",
      "designation_eng": "Senior Assistant Secretary",
      "designation_bng": "সিনিয়র সহকারী সচিব",
      "user_id": 678,
      "username": "100000005360",
      "user_image": None
    },
    {
      "employee_id": 647,
      "employee_name_eng": "Mina Masud Uzzaman",
      "employee_name_bng": "মিনা মাসুদ উজ্জামান",
      "office_id": 57,
      "office_unit_id": 857,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সচিবের দপ্তর",
      "unit_name_en": "Secretary's Office",
      "designation_eng": "Personal Secretary",
      "designation_bng": "সচিবের একান্ত সচিব",
      "user_id": 669,
      "username": "100000006875",
      "user_image": None
    },
    {
      "employee_id": 658,
      "employee_name_eng": "Russel Monzoor",
      "employee_name_bng": "রাসেল মনজুর",
      "office_id": 57,
      "office_unit_id": 857,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সচিবের দপ্তর",
      "unit_name_en": "Secretary's Office",
      "designation_eng": "Personal Secretary",
      "designation_bng": "সচিবের একান্ত সচিব",
      "user_id": 680,
      "username": "100000015765",
      "user_image": None
    },
    {
      "employee_id": 660,
      "employee_name_eng": "Md. Aktar Hossain",
      "employee_name_bng": "মোঃ আকতার হোসেন",
      "office_id": 57,
      "office_unit_id": 878,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রোগ্রাম শাখা",
      "unit_name_en": "Program Section",
      "designation_eng": "Assistant Chief",
      "designation_bng": "সহকারী প্রধান",
      "user_id": 682,
      "username": "100000000477",
      "user_image": None
    },
    {
      "employee_id": 659,
      "employee_name_eng": "Jesmin Parvin",
      "employee_name_bng": "জেসমিন পারভীন",
      "office_id": 57,
      "office_unit_id": 864,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "পার্সোনেল সেবা শাখা",
      "unit_name_en": "Personal Service Section",
      "designation_eng": "Senior Assistant Secretary",
      "designation_bng": "সিনিয়র সহকারী সচিব",
      "user_id": 681,
      "username": "100000015597",
      "user_image": None
    },
    {
      "employee_id": 695,
      "employee_name_eng": "Kazi Mohammad Salim",
      "employee_name_bng": "কাজী মোহাম্মদ সেলিম",
      "office_id": 57,
      "office_unit_id": 868,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অর্গানাইজেশনাল সাপোর্ট এন্ড ইনোভেশন-২ অধিশাখা",
      "unit_name_en": "Organizational Support & Innovation-2 Branch",
      "designation_eng": "Deputy Secretary",
      "designation_bng": "উপ-সচিব",
      "user_id": 717,
      "username": "100000007743",
      "user_image": None
    },
    {
      "employee_id": 652,
      "employee_name_eng": "Parthapratim Deb",
      "employee_name_bng": "পার্থপ্রতিম দেব",
      "office_id": 57,
      "office_unit_id": 858,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রশাসন অনুবিভাগ",
      "unit_name_en": "General Service Wing",
      "designation_eng": "Additional Secretary",
      "designation_bng": "অতিরিক্ত সচিব",
      "user_id": 674,
      "username": "100000004835",
      "user_image": None
    },
    {
      "employee_id": 656,
      "employee_name_eng": "Md. Khairul Amin",
      "employee_name_bng": "মোঃ খায়রুল আমীন",
      "office_id": 57,
      "office_unit_id": 863,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অভ্যন্তরীণ সেবা অধিশাখা",
      "unit_name_en": "Internal Service Branch",
      "designation_eng": "Deputy Secretary",
      "designation_bng": "উপ-সচিব",
      "user_id": 678,
      "username": "100000005360",
      "user_image": None
    },
    {
      "employee_id": 693,
      "employee_name_eng": "মোঃ আব্দুল মান্নান",
      "employee_name_bng": "Md. Abdul Mannan",
      "office_id": 57,
      "office_unit_id": 986,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "জাতীয় সংসদ বিষয়ক অধিশাখা",
      "unit_name_en": "Parliament Branch",
      "designation_eng": "Join Secretary",
      "designation_bng": "যুগ্ম-সচিব",
      "user_id": 715,
      "username": "100000007545",
      "user_image": None
    },
    {
      "employee_id": 661,
      "employee_name_eng": "Assaduzzaman Ripon",
      "employee_name_bng": "আসাদুজ্জামান রিপন",
      "office_id": 57,
      "office_unit_id": 877,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রজেক্ট শাখা",
      "unit_name_en": "Project Section",
      "designation_eng": "Assistant Chief",
      "designation_bng": " সহকারী প্রধান",
      "user_id": 683,
      "username": "100000000541",
      "user_image": None
    },
    {
      "employee_id": 654,
      "employee_name_eng": "Mohammad Manjur Kadir",
      "employee_name_bng": "মোঃ মঞ্জুর কাদির",
      "office_id": 57,
      "office_unit_id": 867,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অর্গানাইজেশনাল সাপোর্ট এন্ড ইনোভেশন-২ অনুবিভাগ",
      "unit_name_en": "Organization Support & Innovation-2 Wing",
      "designation_eng": "Joint Secretary",
      "designation_bng": "যুগ্ম-সচিব",
      "user_id": 676,
      "username": "100000007522",
      "user_image": None
    },
    {
      "employee_id": 694,
      "employee_name_eng": "SAIFUDDIN AHMED MOJUMDER",
      "employee_name_bng": "সাইফুদ্দিন আহম্মদ মজুমদার",
      "office_id": 57,
      "office_unit_id": 871,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অর্গানাইজেশনাল সাপোর্ট এন্ড আইসিটি ইনোভেশন অধিশাখা",
      "unit_name_en": "Organizational Support & ICT Innovation Branch",
      "designation_eng": "Deputy Secretary",
      "designation_bng": "উপ-সচিব",
      "user_id": 716,
      "username": "100000003400",
      "user_image": None
    },
    {
      "employee_id": 651,
      "employee_name_eng": "Susanta Kumar Saha",
      "employee_name_bng": "সুশান্ত কুমার সাহা",
      "office_id": 57,
      "office_unit_id": 875,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "পরিকল্পনা ও উন্নয়ন অনুবিভাগ",
      "unit_name_en": "Planning & Development Wing",
      "designation_eng": "Additional Secretary",
      "designation_bng": "অতিরিক্ত সচিব",
      "user_id": 673,
      "username": "100000004790",
      "user_image": None
    },
    {
      "employee_id": 658,
      "employee_name_eng": "Russel Monzoor",
      "employee_name_bng": "রাসেল মনজুর",
      "office_id": 57,
      "office_unit_id": 995,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রতিমন্ত্রী মহোদয়ের দপ্তর",
      "unit_name_en": "Office of the state Minister",
      "designation_eng": "PS to State Minister",
      "designation_bng": "মাননীয় প্রতিমন্ত্রীর একান্ত সচিব",
      "user_id": 680,
      "username": "100000015765",
      "user_image": None
    },
    {
      "employee_id": 16241,
      "employee_name_eng": "",
      "employee_name_bng": "মো: আব্দুল বারী",
      "office_id": 57,
      "office_unit_id": 995,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রতিমন্ত্রী মহোদয়ের দপ্তর",
      "unit_name_en": "Office of the state Minister",
      "designation_eng": "PS to State Minister",
      "designation_bng": "মাননীয় প্রতিমন্ত্রীর একান্ত সচিব",
      "user_id": 16241,
      "username": "300000007681",
      "user_image": None
    },
    {
      "employee_id": 655,
      "employee_name_eng": "Mohammad Nurul Karim Majumder",
      "employee_name_bng": "মোহাম্মদ নুরুল করিম মজুমদার",
      "office_id": 57,
      "office_unit_id": 859,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "বাজেট অধিশাখা",
      "unit_name_en": "Budget Branch",
      "designation_eng": "Deputy Secretary",
      "designation_bng": "উপ-সচিব",
      "user_id": 677,
      "username": "100000003372",
      "user_image": None
    },
    {
      "employee_id": 653,
      "employee_name_eng": "Touhida Bulbul",
      "employee_name_bng": "তৌহিদা বুলবুল",
      "office_id": 57,
      "office_unit_id": 870,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অর্গানাইজেশনাল সাপোর্ট এন্ড ইনোভেশন-১ অনুবিভাগ",
      "unit_name_en": "Organization Support and Innovation-1 Wing",
      "designation_eng": "Joint Secretary",
      "designation_bng": "যুগ্মসচিব",
      "user_id": 675,
      "username": "100000004552",
      "user_image": None
    },
    {
      "employee_id": 650,
      "employee_name_eng": "Md. Harunur Rashid",
      "employee_name_bng": "মোঃ হারুনুর রশিদ",
      "office_id": 57,
      "office_unit_id": 882,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "আইসিটি অনুবিভাগ",
      "unit_name_en": "ICT Wing",
      "designation_eng": "Additional Secretary",
      "designation_bng": "অতিরিক্ত সচিব",
      "user_id": 672,
      "username": "100000007257",
      "user_image": None
    },
    {
      "employee_id": 12594,
      "employee_name_eng": "Zunaid Ahmed Palak ",
      "employee_name_bng": "জুনাইদ আহ্\u200cমেদ পলক ",
      "office_id": 57,
      "office_unit_id": 995,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রতিমন্ত্রী মহোদয়ের দপ্তর",
      "unit_name_en": "Office of the state Minister",
      "designation_eng": "State Minister",
      "designation_bng": "মাননীয় প্রতিমন্ত্রী",
      "user_id": 12622,
      "username": "500000000131",
      "user_image": None
    },
    {
      "employee_id": 643,
      "employee_name_eng": "Shyam Sunder Sikder",
      "employee_name_bng": "শ্যাম সুন্দর সিকদার",
      "office_id": 57,
      "office_unit_id": 857,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সচিবের দপ্তর",
      "unit_name_en": "Secretary's Office",
      "designation_eng": "Secretary",
      "designation_bng": "সচিব",
      "user_id": 665,
      "username": "100000003361",
      "user_image": None
    },
    {
      "employee_id": 157,
      "employee_name_eng": "N M Ziaul Alam",
      "employee_name_bng": "এন এম জিয়াউল আলম",
      "office_id": 57,
      "office_unit_id": 857,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সচিবের দপ্তর",
      "unit_name_en": "Secretary's Office",
      "designation_eng": "Secretary",
      "designation_bng": "সচিব",
      "user_id": 175,
      "username": "100000003394",
      "user_image": None
    },
    {
      "employee_id": 566,
      "employee_name_eng": "G.M. Jahangir Hossain",
      "employee_name_bng": "জি.এম. জাহাঙ্গীর হোসেন",
      "office_id": 57,
      "office_unit_id": 857,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সচিবের দপ্তর",
      "unit_name_en": "Secretary's Office",
      "designation_eng": "Personal Officer",
      "designation_bng": "ব্যক্তিগত কর্মকর্তা",
      "user_id": 589,
      "username": "200000000142",
      "user_image": None
    },
    {
      "employee_id": 583,
      "employee_name_eng": "Zahid Al Siddique",
      "employee_name_bng": "জাহিদ আল সিদ্দিকী",
      "office_id": 57,
      "office_unit_id": 857,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সচিবের দপ্তর",
      "unit_name_en": "Secretary's Office",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 606,
      "username": "200000000159",
      "user_image": None
    },
    {
      "employee_id": 584,
      "employee_name_eng": "Ahmmed Ali",
      "employee_name_bng": "আহম্মেদ আলী",
      "office_id": 57,
      "office_unit_id": 858,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রশাসন অনুবিভাগ",
      "unit_name_en": "General Service Wing",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 607,
      "username": "200000000160",
      "user_image": None
    },
    {
      "employee_id": 63171,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ মোশারফ হোসেন",
      "office_id": 57,
      "office_unit_id": 859,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "বাজেট অধিশাখা",
      "unit_name_en": "Budget Branch",
      "designation_eng": "Personal Officer",
      "designation_bng": "ব্যক্তিগত কর্মকর্তা",
      "user_id": 63388,
      "username": "200000060897",
      "user_image": None
    },
    {
      "employee_id": 77477,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ মিজানুর রহমান",
      "office_id": 57,
      "office_unit_id": 882,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": None,
      "unit_name_en": None,
      "designation_eng": "office assistant cum computer operator",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 77595,
      "username": "200000072500",
      "user_image": None
    },
    {
      "employee_id": 62769,
      "employee_name_eng": "",
      "employee_name_bng": "কাশমী সুলতানা",
      "office_id": 57,
      "office_unit_id": 860,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "রাজস্ব শাখা",
      "unit_name_en": "Revenue Section",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62988,
      "username": "200000060577",
      "user_image": None
    },
    {
      "employee_id": 62770,
      "employee_name_eng": "",
      "employee_name_bng": "আবদুল্লাহ আল মানসুর",
      "office_id": 57,
      "office_unit_id": 861,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "উন্নয়ন শাখা",
      "unit_name_en": "Development Section",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62989,
      "username": "200000060578",
      "user_image": None
    },
    {
      "employee_id": 58584,
      "employee_name_eng": "",
      "employee_name_bng": "এহছানুল পারভেজ",
      "office_id": 57,
      "office_unit_id": 879,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "উন্নয়ন অধিশাখা",
      "unit_name_en": "Development Branch",
      "designation_eng": "joint secretary",
      "designation_bng": "যুগ্ম-সচিব",
      "user_id": 58818,
      "username": "500000015671",
      "user_image": None
    },
    {
      "employee_id": 12746,
      "employee_name_eng": "test ",
      "employee_name_bng": "মল্লিক মনিরুল ইসলাম",
      "office_id": 57,
      "office_unit_id": 862,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "হিসাব ও অডিট শাখা",
      "unit_name_en": "Accounts & Audit Section",
      "designation_eng": "Cashier",
      "designation_bng": "ক্যাশিয়ার",
      "user_id": 12774,
      "username": "200000009322",
      "user_image": None
    },
    {
      "employee_id": 62771,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ জেইসন জামান শাওন",
      "office_id": 57,
      "office_unit_id": 863,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অভ্যন্তরীণ সেবা অধিশাখা",
      "unit_name_en": "Internal Service Branch",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62990,
      "username": "200000060579",
      "user_image": None
    },
    {
      "employee_id": 578,
      "employee_name_eng": "Md. Nur Hossain Parvez",
      "employee_name_bng": "মোঃ নূর হোসেন পারভেজ",
      "office_id": 57,
      "office_unit_id": 887,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "গবেষণা ও বৃত্তি শাখা",
      "unit_name_en": "Research & Scholarship Section",
      "designation_eng": "Office Assistant Cum Computer Operator",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 601,
      "username": "200000000154",
      "user_image": None
    },
    {
      "employee_id": 62778,
      "employee_name_eng": "",
      "employee_name_bng": "জান্নাতুল ফেরদৌস অন্তরা",
      "office_id": 57,
      "office_unit_id": 863,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অভ্যন্তরীণ সেবা অধিশাখা",
      "unit_name_en": "Internal Service Branch",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62997,
      "username": "200000060586",
      "user_image": None
    },
    {
      "employee_id": 63171,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ মোশারফ হোসেন",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "ই-সার্ভিস অপারেশন শাখা",
      "unit_name_en": "e-Service Operation Section",
      "designation_eng": "Data Entry Operator",
      "designation_bng": "ডাটা এন্ট্রি অপারেটর",
      "user_id": 63388,
      "username": "200000060897",
      "user_image": None
    },
    {
      "employee_id": 76956,
      "employee_name_eng": "",
      "employee_name_bng": "Kawsar Ahmed ",
      "office_id": 57,
      "office_unit_id": 884,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": None,
      "unit_name_en": None,
      "designation_eng": "Data Entry Operator",
      "designation_bng": "ডাটা এন্ট্রি অপারেটর",
      "user_id": 77080,
      "username": "200000072051",
      "user_image": None
    },
    {
      "employee_id": 62772,
      "employee_name_eng": "",
      "employee_name_bng": "প্রণব সিংহ",
      "office_id": 57,
      "office_unit_id": 863,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অভ্যন্তরীণ সেবা অধিশাখা",
      "unit_name_en": "Internal Service Branch",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62991,
      "username": "200000060580",
      "user_image": None
    },
    {
      "employee_id": 62773,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ রফিকুল ইসলাম",
      "office_id": 57,
      "office_unit_id": 863,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অভ্যন্তরীণ সেবা অধিশাখা",
      "unit_name_en": "Internal Service Branch",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62992,
      "username": "200000060581",
      "user_image": None
    },
    {
      "employee_id": 62775,
      "employee_name_eng": "",
      "employee_name_bng": "মোঃ তৌহিদুল ইসলাম",
      "office_id": 57,
      "office_unit_id": 864,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "পার্সোনেল সেবা শাখা",
      "unit_name_en": "Personal Service Section",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62994,
      "username": "200000060583",
      "user_image": None
    },
    {
      "employee_id": 582,
      "employee_name_eng": "Sanowar Hossen",
      "employee_name_bng": "ছানোয়ার হোসেন",
      "office_id": 57,
      "office_unit_id": 866,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "আন্তঃমন্ত্রণালয় শাখা",
      "unit_name_en": "National Parliament & Inter-Ministerial Section",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 605,
      "username": "200000000158",
      "user_image": None
    },
    {
      "employee_id": 62777,
      "employee_name_eng": "",
      "employee_name_bng": "সুবর্না নাসরিন",
      "office_id": 57,
      "office_unit_id": 868,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অর্গানাইজেশনাল সাপোর্ট এন্ড ইনোভেশন-২ অধিশাখা",
      "unit_name_en": "Organizational Support & Innovation-2 Branch",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62996,
      "username": "200000060585",
      "user_image": None
    },
    {
      "employee_id": 63350,
      "employee_name_eng": "",
      "employee_name_bng": "শোভন আহবেদ",
      "office_id": 57,
      "office_unit_id": 882,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "আইসিটি অনুবিভাগ",
      "unit_name_en": "ICT Wing",
      "designation_eng": "",
      "designation_bng": "ব্যক্তিগত কর্মকর্তা",
      "user_id": 63565,
      "username": "200000061054",
      "user_image": None
    },
    {
      "employee_id": 63349,
      "employee_name_eng": "Abdur Rahim",
      "employee_name_bng": "আব্দুর রহিম",
      "office_id": 57,
      "office_unit_id": 10275,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": " মন্ত্রী মহোদয়ের দপ্তর",
      "unit_name_en": "Minister's Office",
      "designation_eng": "office assistant cum computer operator",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 63564,
      "username": "200000061053",
      "user_image": None
    },
    {
      "employee_id": 568,
      "employee_name_eng": "Md. Abdur Rahim",
      "employee_name_bng": "মোঃ আব্দুর রহিম",
      "office_id": 57,
      "office_unit_id": 870,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অর্গানাইজেশনাল সাপোর্ট এন্ড ইনোভেশন-১ অনুবিভাগ",
      "unit_name_en": "Organization Support and Innovation-1 Wing",
      "designation_eng": "Personal Officer",
      "designation_bng": "ব্যক্তিগত কর্মকর্তা",
      "user_id": 591,
      "username": "200000000144",
      "user_image": None
    },
    {
      "employee_id": 64781,
      "employee_name_eng": "Noman",
      "employee_name_bng": "নোমান ",
      "office_id": 57,
      "office_unit_id": 870,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "অর্গানাইজেশনাল সাপোর্ট এন্ড ইনোভেশন-১ অনুবিভাগ",
      "unit_name_en": "Organization Support and Innovation-1 Wing",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 64990,
      "username": "200000062303",
      "user_image": None
    },
    {
      "employee_id": 580,
      "employee_name_eng": "Md. Shoriful Islam",
      "employee_name_bng": "মোঃ শরিফুল ইসলাম",
      "office_id": 57,
      "office_unit_id": 872,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সংস্থা-১ শাখা",
      "unit_name_en": "Organization-1 Section",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 603,
      "username": "200000000156",
      "user_image": None
    },
    {
      "employee_id": 1441,
      "employee_name_eng": "",
      "employee_name_bng": "নাজনীন সুলতানা",
      "office_id": 57,
      "office_unit_id": 873,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "আন্তর্জাতিক ঘটনাবলী সম্পর্কিত",
      "unit_name_en": "International Affairs & Events",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 1463,
      "username": "200000000810",
      "user_image": None
    },
    {
      "employee_id": 12744,
      "employee_name_eng": "test",
      "employee_name_bng": "মোঃ মিনহাজ হোসেন",
      "office_id": 57,
      "office_unit_id": 875,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "পরিকল্পনা ও উন্নয়ন অনুবিভাগ",
      "unit_name_en": "Planning & Development Wing",
      "designation_eng": "Personal Officer",
      "designation_bng": "ব্যক্তিগত কর্মকর্তা",
      "user_id": 12772,
      "username": "200000009321",
      "user_image": None
    },
    {
      "employee_id": 574,
      "employee_name_eng": "Md. Shofikul Islam",
      "employee_name_bng": "মোঃ সফিকুল ইসলাম",
      "office_id": 57,
      "office_unit_id": 875,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "পরিকল্পনা ও উন্নয়ন অনুবিভাগ",
      "unit_name_en": "Planning & Development Wing",
      "designation_eng": "M.L.S.S",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 597,
      "username": "200000000150",
      "user_image": None
    },
    {
      "employee_id": 62779,
      "employee_name_eng": "",
      "employee_name_bng": "আসিফ আহমেদ",
      "office_id": 57,
      "office_unit_id": 876,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "পরিকল্পনা অধিশাখা",
      "unit_name_en": "Planning Branch",
      "designation_eng": "M.L.S.S",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 62998,
      "username": "200000060587",
      "user_image": None
    },
    {
      "employee_id": 12747,
      "employee_name_eng": "tets ",
      "employee_name_bng": "মোহাম্মদ শফিকুল ইসলাম খান",
      "office_id": 57,
      "office_unit_id": 877,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রজেক্ট শাখা",
      "unit_name_en": "Project Section",
      "designation_eng": "Administrative Officer",
      "designation_bng": "প্রশাসনিক কর্মকর্তা",
      "user_id": 12775,
      "username": "200000009323",
      "user_image": None
    },
    {
      "employee_id": 571,
      "employee_name_eng": "Farida Akhter Misty",
      "employee_name_bng": "ফরিদা আক্তার মিষ্টি",
      "office_id": 57,
      "office_unit_id": 877,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রজেক্ট শাখা",
      "unit_name_en": "Project Section",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 594,
      "username": "200000000147",
      "user_image": None
    },
    {
      "employee_id": 563,
      "employee_name_eng": "Muhammad Anwar Hossain",
      "employee_name_bng": "মোহাম্মদ আনোয়ার হোসেন",
      "office_id": 57,
      "office_unit_id": 878,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রোগ্রাম শাখা",
      "unit_name_en": "Program Section",
      "designation_eng": "Administrative Officer",
      "designation_bng": "প্রশাসনিক কর্মকর্তা",
      "user_id": 586,
      "username": "200000000139",
      "user_image": None
    },
    {
      "employee_id": 576,
      "employee_name_eng": "China Akther",
      "employee_name_bng": "চায়না আক্তার",
      "office_id": 57,
      "office_unit_id": 878,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "প্রোগ্রাম শাখা",
      "unit_name_en": "Program Section",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 599,
      "username": "200000000152",
      "user_image": None
    },
    {
      "employee_id": 572,
      "employee_name_eng": "Md. Hanif",
      "employee_name_bng": "মোঃ হানিফ",
      "office_id": 57,
      "office_unit_id": 2694,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "লজিস্টিক সেবা শাখা",
      "unit_name_en": "Logistic Service Section",
      "designation_eng": "Office Assistant Cum Computer Operator",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 595,
      "username": "200000000148",
      "user_image": None
    },
    {
      "employee_id": 577,
      "employee_name_eng": "Md. Hazrat Ali",
      "employee_name_bng": "মোঃ হযরত আলী",
      "office_id": 57,
      "office_unit_id": 879,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "উন্নয়ন অধিশাখা",
      "unit_name_en": "Development Branch",
      "designation_eng": "M.L.S.S.",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 600,
      "username": "200000000153",
      "user_image": None
    },
    {
      "employee_id": 579,
      "employee_name_eng": "Nusrat Jahan",
      "employee_name_bng": "নুছরাত জাহান",
      "office_id": 57,
      "office_unit_id": 869,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "সংস্থা-২ শাখা",
      "unit_name_en": "Organization-2 Section",
      "designation_eng": "Data Entry Operator",
      "designation_bng": "ডাটা এন্ট্রি অপারেটর",
      "user_id": 602,
      "username": "200000000155",
      "user_image": None
    },
    {
      "employee_id": 570,
      "employee_name_eng": "Bholanath Tripura",
      "employee_name_bng": "ভোলানাথ ত্রিপুরা",
      "office_id": 57,
      "office_unit_id": 992,
      "office_name_bn": "তথ্য ও যোগাযোগ প্রযুক্তি বিভাগ",
      "office_name_en": "Secretary's Office",
      "unit_name_bn": "পার্সোনেল সেবা শাখা",
      "unit_name_en": "Personnel Service Section",
      "designation_eng": "Office Assistant Cum Computer Operator",
      "designation_bng": "অফিস সহকারী-কাম-কম্পিউটার অপারেটর",
      "user_id": 593,
      "username": "200000000146",
      "user_image": None
    }
  ]

# unique_username = []
# username_map = []

# print(len(user_info))
# for user in user_info:
# #     print(user['username'])
#     username = user['username']
#     if not username in unique_username:
#         unique_username.append(username)
#         username_map.append(user)

# #     print()

# # print(len(unique_username))
# # print(len(username_map))

# # print(username_map)

# for user in username_map:
#     username = user['username']
#     if username == '200000000146':
#         print(user)

user_map = {}
for user in user_info:
    username = user['username']
    user_map[username] = user