my_file = open('test.txt', 'r')
# content = my_file.read(5)
# print(content)
content = my_file.read()
# print(content)
position = my_file.tell()  # find file pointer
print(position)
my_file.seek(0, 0)
# content = my_file.read()
# print(content)
my_file.close()
